#!/usr/bin/bash

#below input_file is file ".git/COMMIT_EDITMSG" were commits are stored
INPUT_FILE=$1

#it will copy the commit string from ".git/COMMIT_EDITMSG"
START_LINE=`head -n1 $INPUT_FILE`

#initial index value
sum=0

IFS='- ' read -r -a array_value <<< "$START_LINE"

for i in ${!array_value[@]}
do
    sum=`expr $sum + $i`
done


if [ ${sum} == 3 ]; then

USER_NAME=`git config user.name`
TICKET_DIGIT=`awk -F '[0-9]' '{print NF-1}' <<< "${array_value[1]}"`

   if [ ${array_value[0]} != ${USER_NAME} ];  then
        echo "please enter your gitlab username, you may configure/add user name using command 'git config --global user.name "username""
        exit 1
   fi

   if [ "${TICKET_DIGIT}" != "4" ];  then
        echo "INVALID TICKET ID"
        exit 1
   else 
      echo "verify ticket ID ${array_value[1]}"
   fi

else
   echo "pattern must be <developer_username>-<ticketID>-<description> without space eg: john3-4356-Added_Crashanalytics"
   exit 1
fi
